# Generated by Django 2.1.7 on 2019-04-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180429_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='isChose',
            field=models.BooleanField(default=False),
        ),
    ]
