# Generated by Django 2.1.7 on 2019-04-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_order_cartid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='isdelete',
            field=models.BooleanField(default=False),
        ),
    ]
